{
  try {
    test.run();
    return null;
  }
 catch (  AssertionError e) {
    return e;
  }
}
