{
  if (this == ctx.pipeline().last())   logger.error("Exception in response",cause);
  ctx.fireExceptionCaught(cause);
}
