{
  if ((r instanceof Future<?>) && ((Future<?>)r).isDone()) {
    try {
      ((Future<?>)r).get();
    }
 catch (    InterruptedException e) {
      throw new AssertionError(e);
    }
catch (    CancellationException e) {
      logger.debug("Task cancelled",e);
    }
catch (    ExecutionException e) {
      return e.getCause();
    }
  }
  return null;
}
