def assert_raises(exception, method, *args):
    try:
        method(*args)
    except exception:
        return
    raise AssertionError('failed to see expected exception')
