def test_bad(self):
    'ensure bad calls raise exceptions'
    self.assertRaises(KeyError, prepare, ':a :b', a=1)
    self.assertRaises(cql.ProgrammingError, prepare, ':a :b', a=1, b=2, c=3)
    self.assertRaises(cql.ProgrammingError, prepare, 'none', a=1)
