{
  try {
    future.get();
  }
 catch (  ExecutionException ee) {
    throw new RuntimeException(ee);
  }
catch (  InterruptedException ie) {
    throw new AssertionError(ie);
  }
}
